package primeirografo;

import com.alee.laf.WebLookAndFeel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    GrafoLista grafo;

    public Principal() {
        try {
            UIManager.setLookAndFeel(new WebLookAndFeel());
        } catch (Exception e) {
        }

        initComponents();
        ativaBotoes(false);
        campoHistorico.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoCriarGrafo = new javax.swing.JButton();
        botaoAdicionarVertice = new javax.swing.JButton();
        botaoAdicionarAresta = new javax.swing.JButton();
        botaoRemoverAresta = new javax.swing.JButton();
        botaoRemoverVertice = new javax.swing.JButton();
        botaoVerificarVertice = new javax.swing.JButton();
        botaoVerificarAresta = new javax.swing.JButton();
        botaoRetornarArestas = new javax.swing.JButton();
        botaoImprimirGrafo = new javax.swing.JButton();
        botaoPlanar = new javax.swing.JButton();
        botaoLimparHistorico = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoHistorico = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grafos");
        setPreferredSize(new java.awt.Dimension(599, 358));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções"));
        jPanel1.setLayout(new java.awt.GridLayout(11, 0));

        botaoCriarGrafo.setText("Criar Grafo");
        botaoCriarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarGrafoActionPerformed(evt);
            }
        });
        jPanel1.add(botaoCriarGrafo);

        botaoAdicionarVertice.setText("Adicionar Vértice");
        botaoAdicionarVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarVerticeActionPerformed(evt);
            }
        });
        jPanel1.add(botaoAdicionarVertice);

        botaoAdicionarAresta.setText("Adicionar Aresta");
        botaoAdicionarAresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarArestaActionPerformed(evt);
            }
        });
        jPanel1.add(botaoAdicionarAresta);

        botaoRemoverAresta.setText("Remover Aresta");
        botaoRemoverAresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverArestaActionPerformed(evt);
            }
        });
        jPanel1.add(botaoRemoverAresta);

        botaoRemoverVertice.setText("Remover Vértice");
        botaoRemoverVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverVerticeActionPerformed(evt);
            }
        });
        jPanel1.add(botaoRemoverVertice);

        botaoVerificarVertice.setText("Verificar Vértice");
        botaoVerificarVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVerificarVerticeActionPerformed(evt);
            }
        });
        jPanel1.add(botaoVerificarVertice);

        botaoVerificarAresta.setText("Verificar Aresta");
        botaoVerificarAresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVerificarArestaActionPerformed(evt);
            }
        });
        jPanel1.add(botaoVerificarAresta);

        botaoRetornarArestas.setText("Retornar Arestas");
        botaoRetornarArestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRetornarArestasActionPerformed(evt);
            }
        });
        jPanel1.add(botaoRetornarArestas);

        botaoImprimirGrafo.setText("Imprimir Grafo");
        botaoImprimirGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoImprimirGrafoActionPerformed(evt);
            }
        });
        jPanel1.add(botaoImprimirGrafo);

        botaoPlanar.setText("Verificar se é Planar");
        botaoPlanar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPlanarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoPlanar);

        botaoLimparHistorico.setText("Limpar Historico");
        botaoLimparHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparHistoricoActionPerformed(evt);
            }
        });
        jPanel1.add(botaoLimparHistorico);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Histórico"));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 439));
        jPanel2.setLayout(new java.awt.BorderLayout());

        campoHistorico.setColumns(20);
        campoHistorico.setRows(5);
        jScrollPane1.setViewportView(campoHistorico);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel3.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel1.setText("Trabalho de Grafos (M1.1)");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 19, 227));
        jLabel2.setText("Alunos: Eduardo Vinícius Mölleken Tomita, Leonardo Lucas de Melo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ativaBotoes(boolean ativa) {
        botaoAdicionarAresta.setEnabled(ativa);
        botaoAdicionarVertice.setEnabled(ativa);
        botaoImprimirGrafo.setEnabled(ativa);
        botaoRemoverAresta.setEnabled(ativa);
        botaoRemoverVertice.setEnabled(ativa);
        botaoRetornarArestas.setEnabled(ativa);
        botaoVerificarAresta.setEnabled(ativa);
        botaoVerificarVertice.setEnabled(ativa);
        botaoPlanar.setEnabled(ativa);
    }

    private void botaoRemoverVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverVerticeActionPerformed
        String rotulo = null;

        rotulo = JOptionPane.showInputDialog("Qual o rótulo do vértice?", "Digite o rótulo aqui...");

        if ((rotulo == null) || (rotulo.equals(""))) {
            JOptionPane.showMessageDialog(null, "O rótulo preenchido é inválido");
        } else {
            campoHistorico.setText(campoHistorico.getText() + "\n" + grafo.removeVertice(rotulo));
        }
    }//GEN-LAST:event_botaoRemoverVerticeActionPerformed

    private void botaoVerificarVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVerificarVerticeActionPerformed
        String rotulo = null;

        rotulo = JOptionPane.showInputDialog("Qual o rótulo do vértice?", "Digite o rótulo aqui...");

        if ((rotulo == null) || (rotulo.equals(""))) {
            JOptionPane.showMessageDialog(null, "O rótulo preenchido é inválido");
        } else if (grafo.verificaVertice(rotulo)) {
            campoHistorico.setText(campoHistorico.getText() + "\n O Vértice foi encontrado.");
        } else {
            campoHistorico.setText(campoHistorico.getText() + "\n O Vértice não existe.");
        }
    }//GEN-LAST:event_botaoVerificarVerticeActionPerformed

    private void botaoCriarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarGrafoActionPerformed
        if (botaoCriarGrafo.getText().equals("Criar Grafo")) {
            grafo = new GrafoLista();
            botaoCriarGrafo.setText("Remover Grafo");
            ativaBotoes(true);
        } else {
            grafo = null;
            botaoCriarGrafo.setText("Criar Grafo");
            ativaBotoes(false);
        }
    }//GEN-LAST:event_botaoCriarGrafoActionPerformed

    private void botaoAdicionarVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarVerticeActionPerformed
        String rotulo = null;

        rotulo = JOptionPane.showInputDialog("Qual o rótulo do vértice?", "Digite o rótulo aqui...");

        if ((rotulo == null) || (rotulo.equals(""))) {
            JOptionPane.showMessageDialog(null, "O rótulo preenchido é inválido");
        } else {
            Vertice novoVertice = new Vertice(rotulo);

            if (grafo.insereVertice(novoVertice)) {
                campoHistorico.setText(campoHistorico.getText() + "\nO vértice com o rótulo " + rotulo + " foi inserido com sucesso.");
            } else {
                campoHistorico.setText(campoHistorico.getText() + "\nO vértice com o rótulo " + rotulo + " já existe.");
            }
        }

    }//GEN-LAST:event_botaoAdicionarVerticeActionPerformed

    private void botaoAdicionarArestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarArestaActionPerformed
        String verticeOrigem = null;
        String verticeDestino = null;

        verticeOrigem = JOptionPane.showInputDialog("Qual o rótulo do vértice de origem?", "Digite o rótulo aqui...");

        if ((verticeOrigem == null) || (verticeOrigem.equals(""))) {
            JOptionPane.showMessageDialog(null, "O rótulo preenchido é inválido");
        } else {

            verticeDestino = JOptionPane.showInputDialog("Qual o rótulo do vértice de destino?", "Digite o rótulo aqui...");

            if ((verticeDestino == null) || (verticeDestino.equals(""))) {
                JOptionPane.showMessageDialog(null, "O rótulo preenchido é inválido");
            } else if (grafo.inserirAresta(verticeOrigem, verticeDestino)) {
                campoHistorico.setText(campoHistorico.getText() + "\n A aresta foi inserida com sucesso.");
            } else {
                campoHistorico.setText(campoHistorico.getText() + "\n Não foi possível inserir a aresta.");
            }
        }
    }//GEN-LAST:event_botaoAdicionarArestaActionPerformed

    private void botaoRemoverArestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverArestaActionPerformed
        String verticeOrigem = null;
        String verticeDestino = null;

        verticeOrigem = JOptionPane.showInputDialog("Qual o rótulo do vértice de origem?", "Digite o rótulo aqui...");

        if ((verticeOrigem == null) || (verticeOrigem.equals(""))) {
            JOptionPane.showMessageDialog(null, "O rótulo preenchido é inválido");
        } else {

            verticeDestino = JOptionPane.showInputDialog("Qual o rótulo do vértice de destino?", "Digite o rótulo aqui...");

            if ((verticeDestino == null) || (verticeDestino.equals(""))) {
                JOptionPane.showMessageDialog(null, "O rótulo preenchido é inválido");
            } else {
                campoHistorico.setText(campoHistorico.getText() + "\n" + grafo.removeAresta(verticeOrigem, verticeDestino));
            }
        }
    }//GEN-LAST:event_botaoRemoverArestaActionPerformed

    private void botaoVerificarArestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVerificarArestaActionPerformed
        String verticeOrigem = null;
        String verticeDestino = null;

        verticeOrigem = JOptionPane.showInputDialog("Qual o rótulo do vértice de origem?", "Digite o rótulo aqui...");

        if ((verticeOrigem == null) || (verticeOrigem.equals(""))) {
            JOptionPane.showMessageDialog(null, "O rótulo preenchido é inválido");
        } else {

            verticeDestino = JOptionPane.showInputDialog("Qual o rótulo do vértice de destino?", "Digite o rótulo aqui...");

            if ((verticeDestino == null) || (verticeDestino.equals(""))) {
                JOptionPane.showMessageDialog(null, "O rótulo preenchido é inválido");
            } else if (grafo.verificaAresta(verticeOrigem, verticeDestino)) {
                campoHistorico.setText(campoHistorico.getText() + "\n A aresta foi encontrada.");
            } else {
                campoHistorico.setText(campoHistorico.getText() + "\n A aresta não existe.");
            }
        }
    }//GEN-LAST:event_botaoVerificarArestaActionPerformed

    private void botaoRetornarArestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRetornarArestasActionPerformed
        String rotulo = null;

        rotulo = JOptionPane.showInputDialog("Qual o rótulo do vértice?", "Digite o rótulo aqui...");

        if ((rotulo == null) || (rotulo.equals(""))) {
            JOptionPane.showMessageDialog(null, "O rótulo preenchido é inválido");
        } else {
            ArrayList<Aresta> arestas = grafo.retornarArestas(rotulo);

            if (arestas != null) {
                campoHistorico.setText(campoHistorico.getText() + "\nArestas para o Vértice " + rotulo + ": ");
                for (Aresta aresta : arestas) {
                    campoHistorico.setText(campoHistorico.getText() + aresta.getVertice() + " | ");
                }
            } else {
                campoHistorico.setText(campoHistorico.getText() + "\nO vértice não possui arestas.");
            }
        }
    }//GEN-LAST:event_botaoRetornarArestasActionPerformed

    private void botaoImprimirGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoImprimirGrafoActionPerformed
        campoHistorico.setText(campoHistorico.getText() + "\n" + grafo.imprimeGrafo());
    }//GEN-LAST:event_botaoImprimirGrafoActionPerformed

    private void botaoPlanarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPlanarActionPerformed
        if (grafo.listaVertice.size() <= 0) {
            campoHistorico.setText(campoHistorico.getText() + "\nNão existem vértices.");
        } else {

            if (grafo.verificaPlanar()) {
                campoHistorico.setText(campoHistorico.getText() + "\nO grafo pode ser planar.");
            } else {
                campoHistorico.setText(campoHistorico.getText() + "\nO grafo não é planar.");
            }
        }
    }//GEN-LAST:event_botaoPlanarActionPerformed

    private void botaoLimparHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparHistoricoActionPerformed
        campoHistorico.setText("");
    }//GEN-LAST:event_botaoLimparHistoricoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionarAresta;
    private javax.swing.JButton botaoAdicionarVertice;
    private javax.swing.JButton botaoCriarGrafo;
    private javax.swing.JButton botaoImprimirGrafo;
    private javax.swing.JButton botaoLimparHistorico;
    private javax.swing.JButton botaoPlanar;
    private javax.swing.JButton botaoRemoverAresta;
    private javax.swing.JButton botaoRemoverVertice;
    private javax.swing.JButton botaoRetornarArestas;
    private javax.swing.JButton botaoVerificarAresta;
    private javax.swing.JButton botaoVerificarVertice;
    private javax.swing.JTextArea campoHistorico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
